<?php

namespace App\Model\Orm\Repository;

use App\Model\Orm\Entity\Azyl;
use App\Model\Orm\Entity\Conversations;
use App\Model\Orm\Entity\Users;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;

class ConversationsRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, string $entityClass = Conversations::class)
    {
        parent::__construct($em, $em->getClassMetadata($entityClass));
    }

    public function findOneBy(array $criteria, ?array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
    }

    public function findOneById(string $id): ?Conversations
    {
        return $this->findOneBy(['id' => $id]);
    }

    public function findByUser(Users $user): ?array
    {
        return $this->findBy(['user' => $user]);
    }

    public function findByAzyl(Azyl $azyl): ?array
    {
        return $this->findBy(['azyl' => $azyl]);
    }

    public function findByUserAndAzyl(Users $user, Azyl $azyl): ?array
    {
        return $this->findBy(['user' => $user, 'azyl' => $azyl],['adoption' => 'ASC']);
    }

    public function findSupportConversationByUser(Users $user): ?Conversations
    {
        return $this->findOneBy(['user' => $user, 'azyl' => null]);
    }


    public function save(Conversations $conversations): void
    {
        $this->getEntityManager()->persist($conversations);
        $this->getEntityManager()->flush();
    }

    public function remove(Conversations $conversations): void
    {
        $this->getEntityManager()->remove($conversations);
    }

    public function flush(): void
    {
        $this->getEntityManager()->flush();
    }
}