<?php

declare(strict_types=1);

namespace App\Model\Orm\Repository;

use App\Model\Orm\Entity\Collections;
use App\Model\Orm\Entity\SystemSettings;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

class SystemSetingsRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em, string $class = SystemSettings::class)
    {
        parent::__construct($em, $em->getClassMetadata($class));
    }

    public function findOneBy(array $criteria, ?array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy); // TODO: Change the autogenerated stub
    }

    /**
     * @throws NonUniqueResultException
     * @throws NoResultException
     */
    public function lastSetings()
    {
        return $this->createQueryBuilder('s')
            ->where('s.depricated = :depricated') // Použití parametru
            ->setParameter('depricated', false)   // Nastavení hodnoty parametru
            ->orderBy('s.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function save($systemSetings): void
    {
        $this->getEntityManager()->persist($systemSetings);
        $this->getEntityManager()->flush();

    }

}